name: build-briggs-birds
run-name: Building briggsbirds.com
on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
jobs:
  build-briggs-birds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
